'use strict'

export const MEMBERS_LOOKUP = 'MEMBERS_LOOKUP'
export const MEMBERS_LOOKUP_SUCCEEDED = 'MEMBERS_LOOKUP_SUCCEEDED'
export const MEMBERS_LOOKUP_FAILED = 'MEMBERS_LOOKUP_FAILED'

export const MEMBERS_CREATE_REQUEST = 'MEMBERS_CREATE_REQUEST'
export const MEMBERS_CREATE_SUCCEEDED = 'MEMBERS_CREATE_SUCCEEDED'
export const MEMBERS_CREATE_FAILED = 'MEMBERS_CREATE_FAILED'

export const MEMBER_EDIT_REQUEST = 'MEMBER_EDIT_REQUEST'
export const MEMBER_EDIT_SUCCEEDED = 'MEMBER_EDIT_SUCCEEDED'
export const MEMBER_EDIT_FAILED = 'MEMBER_EDIT_FAILED'

export const MEMBER_LOOKUP = 'MEMBER_LOOKUP'
export const MEMBER_LOOKUP_SUCCEEDED = 'MEMBER_LOOKUP_SUCCEEDED'
export const MEMBER_LOOKUP_FAILED = 'MEMBER_LOOKUP_FAILED'
