'use strict';

export const RETRIEVE_TRANSFERS = 'RETRIEVE_TRANSFERS';
export const RETRIEVE_TRANSFERS_SUCCEEDED = 'RETRIEVE_TRANSFERS_SUCCEEDED';
export const RETRIEVE_TRANSFERS_FAILED = 'RETRIEVE_TRANSFERS_FAILED';
