'use strict';

export const RETRIEVE_POSITIONS = 'RETRIEVE_POSITIONS';
export const RETRIEVE_POSITIONS_SUCCEEDED = 'RETRIEVE_POSITIONS_SUCCEEDED';
export const RETRIEVE_POSITIONS_FAILED = 'RETRIEVE_POSITIONS_FAILED';
